# Generated by Django 6.0 on 2025-12-15 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_sociallink_alter_about_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sociallink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='account_url',
            field=models.URLField(max_length=250),
        ),
    ]
